### ISSUE TITLE
fixExtent后立即setZoom, 不改变层级平移地图第二次fixExtnt无效

### ISSUE THREAD

**Issue by just-ads** [maptalks/maptalks.js#1555] opened 2021-12-30 11:51 UTC
https://user-images.githubusercontent.com/50706050/147749510-d7846409-070d-444c-92df-2643cf2d6c0b.mp4

**Comment by fuzhenn** [comment] 2021-12-30 11:52
duplicate of #1554

**Closed as completed by fuzhenn** 2021-12-30 11:52 UTC
