### ISSUE TITLE
Loading Esri Feature Layer and Dynamic Map Layer

### ISSUE THREAD

**Issue by praveen-238** [maptalks/maptalks.js#731] opened 2018-07-29 18:34 UTC
**maptalks's version and what browser you use?**
----v0.40.2

**Issue description**
----Can we load esri feature layers and dynamic layers using maptalks? I have tried with 'maptalks.esri' but it is breaking with other urls other than the example. Please let me know if there are any other ways.

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment] 2018-07-31 03:36
Thanks.
This issue is a duplicate of #730 , we can have further discuss there.

**Closed as completed by fuzhenn** 2018-07-31 03:36 UTC
