### ISSUE TITLE
marker开启动画，导致marker有时候点不中

### ISSUE THREAD

**Issue by MaJiaXuan** [maptalks/maptalks.js#2173] opened 2023-12-29 08:30 UTC
**maptalks's version and what browser you use?**
----
谷歌 120.0.6099.110

**Issue description**
----
marker开启动画，导致marker有时候点不中

**Please provide a reproduction URL (on any jsfiddle like site)**
----
[图标开启动画，导致图标有时候点不中.zip](https://github.com/maptalks/maptalks.js/files/13792034/default.zip)

**Comment by fuzhenn** [comment] 2023-12-29 08:35
duplicate of maptalks/issues#565

**Closed as completed by fuzhenn** 2023-12-29 08:35 UTC
