### ISSUE TITLE
Centre point based on markers and zoom in maximum while still fitting all markers in view

### ISSUE THREAD

**Issue by rbsam176** [maptalks/maptalks.js#1657] opened 2022-04-17 13:46 UTC
**maptalks's version and what browser you use?**
----
v1.0.0-rc.4, Chrome/Safari

**Issue description**
----
I've had a look through the documentation but can't seem to find out if this is possible, apologies if this has been covered already. Is it possible to set the centre coordinate of a map to be the centre point between an array of markers, and is it possible to set the zoom to zoom in the most it can while fitting all markers in view? 

If this isn't possible natively, can anyone point me in the direction of how I could calculate the centre coordinate between an array of marker coordinates, and how I could determine the zoom level to fit them all in view?

Thanks for the help!

**Please provide a reproduction URL (on any jsfiddle like site)**
----
N/A

**Comment by fuzhenn** [comment] 2022-04-18 10:18
There is no native methods, but you can implement it as below.
Assuming there are n markers:
* caculate extent of all markers:
```js
// find xmin, ymin, xmax, ymax of all markers
const extent = new maptalks.Extent(xmin, ymin, xmax, ymax);
```
* Get center of the extent
```js
const center = extent.getCenter();
```
* Get map's fit zoom for the extent
```js
// change true to false if you want an integer zoom instead of a fractional zoom
const zoom = map.getFitZoom(extent, true);
```
* Set map's view
```js
map.setCenterAndZoom(center, zoom);
```


as this is not a bug or a feature request, closing this issue for now.

**Closed as completed by fuzhenn** 2022-04-18 10:18 UTC
