### ISSUE TITLE
地图自适应层级缩放问题

### ISSUE THREAD

**Issue by liulianfan** [maptalks/maptalks.js#1181] opened 2020-08-04 08:03 UTC
**maptalks's version and what browser you use?**
----
最新

**Issue description**
----
当地图存在倾斜角度时，fitExtent方法存在偶然性的计算错误情况

**Please provide a reproduction URL (on any jsfiddle like site)**
----
https://maptalks.org/examples/en/map/fit-extent/#map_fit-extent

**Comment by fuzhenn** [comment] 2020-10-09 10:06
duplicate of #1203

**Closed as completed by fuzhenn** 2020-10-09 10:06 UTC
