### ISSUE TITLE
能做2.5D的geoJson吗

### ISSUE THREAD

**Issue by MaJiaXuan** [maptalks/maptalks.js#948] opened 2019-07-09 03:10 UTC
**maptalks's version and what browser you use?**
----

**Issue description**
能做2.5D的geoJson吗
----

**Please provide a reproduction URL (on any jsfiddle like site)**
----

**Comment by fuzhenn** [comment] 2019-07-10 02:26
2.5D的geojson是指？

**Comment by MaJiaXuan** [comment] 2019-07-10 02:27
@fuzhenn 
![image](https://user-images.githubusercontent.com/24503453/60935698-5e0f5700-a2fd-11e9-9b24-100c64ae7435.png)

**Comment by fuzhenn** [comment] 2019-07-10 04:38
duplicate of #945

**Closed as completed by fuzhenn** 2019-07-10 04:38 UTC
